version: '3'
services:
  odoo15:
    build: ./
    container_name: odoo15
    image: myodoo:1.3
    depends_on:
      - odoo_db
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/lib/odoo
      - ./config:/etc/odoo
      #Subir dos carpetas fuera de la actual
      - e:/repos/odoo_addons:/mnt/extra-addons
    environment:
      - HOST=odoo_db
      - LANG=es_MX.UTF-8
    restart: always
  odoo_db:
    container_name: odoo_db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db_data:/var/lib/postgresql/data/pgdata
    restart: always
