version: '3'
services:
  mail:
    container_name: posteio
    image: analogic/poste.io 
    expose:
      - 25
      - 80
      - 443
      - 110
      - 143
      - 465
      - 587
      - 993
      - 995
    environment:
      - HTTPS=ON
    network_mode: "host"
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always